version: '3.7'
services:
  client:
    stdin_open: true
    build:
      context: ./client
      dockerfile: Dockerfile
    image: bits_stack_client
    container_name: bits_stack_client_container
    command: npm start
    volumes:
      - ./client/:/usr/src/bits_stack/client/
      - /usr/src/bits_stack/client/node_modules
    ports:
      - '80:3000'
    depends_on:
      - api
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
      - bits_stack_network
    restart: always
  api:
    build:
      context: ./server
      dockerfile: Dockerfile
    image: bits_stack_server
    container_name: bits_stack_server_container
    restart: always
    command: npm run server
    volumes:
      - ./server/:/usr/src/bits_stack/server/
      - /usr/src/bits_stack/server/node_modules
    ports:
      - '5000:5000'
    depends_on:
      - mongo
    environment:
      - NODE_ENV=development
      - MONGO_URL=mongodb://mongo:27017/bits_stack
      - CHOKIDAR_USEPOLLING=true
    networks:
      - bits_stack_network 
  mongo:
    image: mongo
    restart: always
    container_name: bits_stack_mongo_container
    ports:
      - '27017:27017'
    networks:
      - bits_stack_network
    volumes:
      - data_mongo:/data/db

networks:
  bits_stack_network:
      driver: bridge
    
volumes:
    data_mongo:
    node_modules:
    web-root:
      driver: local